#!/usr/bin/env python3
# coding: utf-8
import sys
from itertools import zip_longest


def errmsg(*args, **kwargs):
    print(*args, file=sys.stderr, **kwargs)


def floatdiff(first_file, second_file, precision):
    for (line1, line2) in zip_longest(first_file, second_file):
        if (not line1) ^ (not line2):
            return True
        for (token1, token2) in zip_longest(line1.split(), line2.split()):
            if token1 != token2:
                try:
                    f1, f2 = float(token1), float(token2)
                except (ValueError, TypeError):
                    print(token1, "!=", token2)
                    return True
                else:
                    if abs(f1 - f2) > precision:
                        print(token1, "!=", token2)
                        return True
                    else:
                        print("Considering", f1, "==", f2)
    return False


try:
    import unittest
except ImportError:
    pass
else:
    class FloatDiffTests(unittest.TestCase):
        def test_one(self):
            file1 = [
                "a 0.01",
                "0.123"
            ]

            file2 = [
                "a 0.01000123",
                "0.124"
            ]

            self.assertFalse(floatdiff(file1, file2, 0.1))
            self.assertFalse(floatdiff(file1, file2, 0.01))
            self.assertTrue(floatdiff(file1, file2, 0.001))


def main():
    progname = sys.argv.pop(0)

    precision = 0.0000001

    if len(sys.argv) == 3:
        precision_token = sys.argv.pop(2)
        try:
            precision = float(precision_token)
        except ValueError:
            errmsg("Expected float precision, got '{}'" \
                   .format(precision_token))
            exit(3)

    if len(sys.argv) != 2:
        errmsg("Usage: {progname} <first_file> <second_file> [precision]" \
               .format(progname=progname))
        exit(2)

    first, second = sys.argv
    with open(first, "r") as first_file:
        with open(second, "r") as second_file:
            exit(floatdiff(first_file, second_file, precision))


if __name__ == "__main__":
    main()
